version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: $USER
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./db/schema/shared-data-model.sql:/docker-entrypoint-initdb.d/shared-data-model.sql

volumes:
  postgres-volume: